---
sidebar: sidebar
permalink: use/remediate-review.html
keywords: bluexp, operational resiliency, remediate, security risk remediation
summary: The Risk remediation service identifies security risks on your on-premises ONTAP cluster.     
---

= Review security risk issues
:hardbreaks:
:icons: font
:imagesdir: ../media/use/

[.lead]
The Risk remediation service identifies security risks on your on-premises ONTAP cluster. 

Reviewing the risks involves the following processes: 

* Create a Connector in BlueXP (if one does not already exist for the Risk remediation service). 
* Discover the cluster (if one does not already exist for the service). 
* Execute the remediation or download an Ansible playbook.
* View the remediation status.



.Steps

. From the left BlueXP navigation, select *Health* > *Operational resiliency* > *Risk Remediation*.

. In the list of risks, sort by the Impact level column to see the highest risks first. 

. Select the risk and select *Remediate risk*. 

. Do one of the following: 
+
* For each cluster, select *Remediate*. 
+
This action deploys the Connector (if not already done), discovers the cluster, downloads the fix and automatically implements the fix on the selected cluster.  Continue with link:../use/remediate-auto.html[Remediate risk issues automatically].

* To remediate yourself, select *Download* to download an Ansible playbook that you use to fix the issue yourself. Continue with link:../use/remediate-ansible.html[Remediate with an Ansible playbook].
