---
sidebar: sidebar
permalink: use/remediate-overview.html
keywords: operational resiliency, remediate, risk remediation, security risk
summary: The NetApp BlueXP operational resiliency service uses AI to determine security risks. 
---

= Review and remediate security risk issues
:hardbreaks:
:icons: font
:imagesdir: ../media/use/

[.lead]
BlueXP operational resiliency enables you to review security risks related to firmware issues and implement remediations. 

Recommendations are provided at the system or node level.


After reviewing risks, you can remediate those risks in two ways: 

*	Have the service execute the remediation, which will fix the issue for you.  
*	Download an Ansible playbook, an open-source deployment system that enables you to run configuration tasks, and you perform the actions suggested in the playbook. 


Using the operational resiliency service, you can accomplish these goals: 

* link:../use/remediate-review.html[Review security risk issues]
* link:../use/remediate-auto.html[Remediate automatically]
* link:../use/remediate-ansible.html[Remediate using an Ansible playbook]
* link:../use/remediate-status.html[Determine the risk remediation status]