---
sidebar: sidebar
permalink: get-started/intro.html
keywords: how bluexp operational resiliency works, what is operational resiliency, bluexp
summary: Operational resiliency is a category of services that help you analyze alerts and events to maintain the health, uptime, and performance of services and solutions. Using the Operational resiliency’s Risk remediation service and its automated IT operational remediation suggestions, you can implement suggested remediations before an outage or failure occurs. 

---

= Learn about the Operational resiliency service
:hardbreaks:
:icons: font
:imagesdir: ../media/concepts/

[.lead]
Operational resiliency is a category of services that help you analyze alerts and events to maintain the health, uptime, and performance of services and solutions. Using the Operational resiliency’s Risk remediation service and its automated IT operational remediation suggestions, you can implement suggested remediations before an outage or failure occurs. 

Risk remediation is a service for BlueXP that implements remediations to NetApp ONTAP clusters based on NetApp Digital Advisor (formerly Active IQ) guidance. The service detects security vulnerabilities, such as firmware and software configuration issues. 

== Benefits of using the Operational resiliency service 

The Operational resiliency service offers the following benefits: 

* Automated procedures for corrections on the cluster
* Summary view in the Dashboard showing the state of each risk remediation
* Log that lets you track the different actions taken


== What you can do with the Operational resiliency service 

Using the Operational resiliency service, you can accomplish the following goals: 

* Use automated workflows that help you detect risks impacting your storage environment and take actions to mitigate them. 

* Review and act on operational recommendations, such as issues related to security vulnerabilities. 

== Cost

NetApp doesn’t charge you for using the service.

== Supported environments 

The Operational resiliency service analyzes on-premises NetApp ONTAP clusters. 