---
sidebar: sidebar
permalink: get-started/intro.html
keywords: how bluexp operational resiliency works, what is operational resiliency, bluexp
summary: BlueXP operational resiliency is a service that helps you analyze alerts and events to maintain the health, uptime, and performance of services and solutions. Using the operational resiliency service and its automated IT operational remediation suggestions, you can implement suggested remediations before an outage or failure occurs. 

---

= Learn about BlueXP operational resiliency
:hardbreaks:
:icons: font
:imagesdir: ../media/concepts/

[.lead]
BlueXP operational resiliency is a service thats helps you analyze alerts and events to maintain the health, uptime, and performance of services and solutions. Using the operational resiliency service and its automated IT operational risk remediation suggestions, you can implement suggested remediations before an outage or failure occurs. 

This BlueXP service implements remediations to NetApp ONTAP clusters based on BlueXP digital advisor (Active IQ) guidance. The service detects security vulnerabilities, such as firmware and software configuration issues. 

== Benefits of using BlueXP operational resiliency 

BlueXP operational resiliency offers the following benefits: 

* Automated procedures for corrections on the cluster
* Summary view in the Dashboard showing the state of each risk remediation
* Log that lets you track the different actions taken


== What you can do with BlueXP operational resiliency 

Using the operational resiliency service, you can accomplish the following goals: 

* Use automated workflows that help you detect risks impacting your storage environment and take actions to mitigate them. 

* Review and act on operational recommendations, such as issues related to security vulnerabilities. 

== Cost

NetApp doesn’t charge you for using the service.

== Supported environments 

BlueXP operational resiliency analyzes on-premises NetApp ONTAP clusters. 