---
sidebar: sidebar
permalink: get-started/prerequisites.html
keywords: what are bluexp operational resiliency requirements, economic efficiency prerequisites
summary: Get started with the BlueXP operational resiliency service by verifying support for your environment, network access, login and web browser.
---

= BlueXP operational resiliency prerequisites
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

[.lead]
Get started by verifying the readiness of your operational environment, login, network access, and web browser.

To use the operational resiliency service, you should ensure that your environment meets all requirements. 

* Your environment must meet all BlueXP requirements including a login and network access from a web browser. 
+
Refer to the https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-standard-mode.html[BlueXP Quick start^] and https://docs.netapp.com/us-en/bluexp-setup-admin/reference-networking-saas-console.html[BlueXP networking information^].


* The service requires that all clusters are monitored by BlueXP digital advisor (Active IQ), which requires AutoSupport enabled on the asset. Refer to https://docs.netapp.com/us-en/active-iq/index.html[BlueXP digital advisor documentation^].

* You need to have access credentials to the clusters. 

* For automatic remediation, a BlueXP Connector is required. It is helpful if the BlueXP Connector is in place and enabled and the ONTAP system is discovered before you initiate the remediation using BlueXP operational resiliency. If the Connector is not in place, the operational resiliency service walks you through those processes. If instead you remediate using an Ansible file, the BlueXP Connector is not required. 




