---
sidebar: sidebar
permalink: get-started/prerequisites.html
keywords: what are bluexp operational resiliency requirements, economic efficiency prerequisites
summary: Get started with the BlueXP operational resiliency service by verifying support for your environment, network access, login and web browser.
---

= Operational resiliency prerequisites
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

[.lead]
Get started by verifying the readiness of your operational environment, login, network access, and web browser.

To use the operational resiliency service, you should ensure that your environment meets all requirements. 

* Your environment must meet all BlueXP requirements including a login and network access from a web browser. 
+
Refer to the https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-quick-start-standard-mode.html[BlueXP Quick start^] and https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-networking-saas-console.html[BlueXP networking information^].


* The service requires that all clusters are monitored by Digital Advisor (formerly Active IQ Digital Advisor). Refer to https://docs.netapp.com/us-en/active-iq/index.html[Digital Advisor documentation^].

* You need to have access credentials to the clusters. 

* While not a requirement, it is helpful if the BlueXP Connector is in place and enabled and the ONTAP system is discovered. If not, the operational resiliency service walks you through those processes. 

