---
sidebar: sidebar
permalink: get-started/setup.html
keywords: bluexp, operational resiliency, risk remediate
summary: Rather than add capacity or tier cold data, you can choose no action required at this time and set reminders for yourself to check again after 30, 60, or 90 days.  
---

= Set up the operational resiliency service
:hardbreaks:
:icons: font
:imagesdir: ../media/get-started/

[.lead]
The first step on the path to using the operational resiliency service is making data available from the monitoring tools in your environment. 

Setting up the service involves the following steps: 

* Review link:../get-started/prerequisites.html[prerequisites] to ensure that your environment is ready
* Optionally  before using the service, create a Connector in BlueXP
* Optionally before using the service, discover the cluster in BlueXP

== Create a Connector in BlueXP
A BlueXP Connector includes credentials to NetApp ONTAP machines so that the Operational resiliency service can advise on security risks and execute remediations.

You can create a Connector directly in BlueXP and use that Connector in the operational resiliency service. Or, you can initiate the process of looking at the cluster and in the middle of that process, deploy the Connector. 

To create a Connector in BlueXP before using the service, refer to BlueXP documentation that describes https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html[how to create a connector^]. 


== Discover the cluster in BlueXP 

Part of the setup involves identifying the cluster name, IP, user name, and password within BlueXP.

For instructions, refer to BlueXP documentation that explains https://docs.netapp.com/us-en/cloud-manager-setup-admin/index.html[how to identify the cluster^].

